<!DOCTYPE html>
<html>
    <head>
        <title>Flappy bird?</title>
        <link rel="stylesheet" href="/css/flappyBird.css">
    </head>
    <body>
        <h1>Flappy bird</h1><button onclick="start()" id="startKnapp">Start</button><button onclick="debug()">trykk</button>
        <div id="main">
            <div id="bird">
                <p>bird</p>
            </div>

        </div>
        
    </body>
    <script src="/js/flappyBird.js"></script>
</html>